# Generated by Django 4.1 on 2022-08-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
