# Generated by Django 4.1 on 2022-08-16 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_roommember_join_time_roommember_leave_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room', to_field='name'),
        ),
    ]
